#!/usr/bin/env bash
#this script will display the content of file /etc/passwd will display only username, user id, Home directory path for the user.

while IFS=: read -r username password uid gid full_name home_dir shell
do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home_dir"
    echo
done < /etc/passwd

