#!/usr/bin/env bash
#Write a Bash script that displays the content of the /etc/passwd, using the while loop + IFS

IFS=':'

# Open the /etc/passwd file and read each line
while read -r username password user_id group_id user_info home_directory shell; do
  echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $user_info."
done < /etc/passwd
