#!/usr/bin/env bash
#This script will display the 10 line "Best School" at the 9 line will display "Best School" and then Hi

i=1 
while [ $i -le 10 ]
do 

if [ $i -eq 9 ]
then
    echo "Best School"
    echo "Hi"
else
    echo "Best School"
fi 
i=$((i + 1))
done
