#!/usr/bin/env bash
#This script will display the content ot current directory in a list format w
here only the part of the name after the first dash is displayed

for file in *; do
  if [[ "$file" == *-* ]]; then
    echo "${file#*-}"
  else
    echo "$file"
  fi
done
