#!/usr/bin/env bash
#This script will display information about the school file

if [[ -e school ]]; then
    if [[ -f school ]]; then
        echo "school file exists and is a regular file"

        if [[ -s school ]]; then
            echo "school file is not empty"
        else
            echo "school file is empty"
        fi
    elif [[ -d school ]]; then
        echo "school exists but it's a directory"
    fi
else
    echo "school file does not exist"
fi
