#!/usr/bin/env bash
#This script will display information about the school file

i="school"
if [[ -e $i ]]; then
    if [[ -f $i ]]; then
        echo "$i file exists and is a regular file"

        if [[ -s $i ]]; then
            echo "$i file is not empty"
        else
            echo "$i file is empty"
        fi
    elif [[ -d $i ]]; then
        echo "$i exists but it's a directory"
    fi
else
    echo "$i file does not exist"
fi
