#!/usr/bin/env bash
#This a script that Process and PID fil
clean_up() {
    echo "Cleaning up..."
    rm -f /var/run/myscript.pid
    exit 0
}
handle_sigterm() {
    echo "I hate the kill command"
    clean_up
}
handle_sigint() {
    echo "Y U no love me?!"
}
handle_sigquit() {
    echo "Received SIGQUIT. Cleaning up and exiting..."
    clean_up
}
echo $$ > "/var/run/myscript.pid"

trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT
trap 'handle_sigquit' SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
